### PR TITLE
fix: manage near and evm nonces using mutex

### LINKED ISSUE #238: [OmniRelayer]: issue with asynchronous method calls
Image

Right now, relayer is gathering all new events every 10 seconds and tries to process each event at the same time and this causes issue with nonces. For example, if we have 4 different init transfer events on Near and we want to sign them all together we need to create 4 different nonces for each of them. But current logic tries to sign all `sign_transfer` together using one access key and same nonce. Therefore, only one event will be processed correctly and all other will fail

Easiest solution:
Process events on NEAR one by one after making sure that event was included into the block

Additional solution:
Figure out how to process events asynchronously correctly. Maybe by providing some offset to sdk that will be used for nonce

Additional question:
Will other chains have the same issue?

### PR DESCRIPTION
**Pull request by frolvanya**
Now it can handle multiple events at the same time:
image

closes #238

### CODE REVIEW

**Comment by race-of-sloths** [comment]
@frolvanya Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Weekly streak is on the road, smart strategy! Secure your streak with another PR!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://race-of-sloths.com/images/bot-banner-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://race-of-sloths.com/images/bot-banner-light.svg">
    Shows inviting banner with latest news.
</picture>](https://race-of-sloths.com/latest-news)

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/frolvanya?type=bot&pr=Near-One/omni-bridge/243&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/frolvanya?type=bot&pr=Near-One/omni-bridge/243&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/frolvanya)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/frolvanya)

For maintainers:
- Score pull requests that participate in the Race of Sloths and receive a reward
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

File: omni-relayer/src/config.rs [hunk 1]
```diff
@@ -15,6 +18,18 @@ pub fn get_private_key(chain_kind: ChainKind) -> String {
     std::env::var(env_var).unwrap_or_else(|_| panic!("Failed to get `{env_var}` env variable"))
 }
 
+pub fn get_evm_address(chain_kind: ChainKind) -> Address {
```
Comment (karim-en) [inline omni-relayer/src/config.rs:21]: let's rename it to `get_relayer_evm_address`

**Review by karim-en — CHANGES_REQUESTED** [review]

File: omni-relayer/src/config.rs (hunk 1 above)
Comment (frolvanya) [reply omni-relayer/src/config.rs]: Fixed in https://github.com/Near-One/omni-bridge/pull/243/commits/cbee1241407789953f144eb3d935c0fbf203e806

File: omni-relayer/src/utils/nonce.rs [hunk 2]
```diff
@@ -0,0 +1,197 @@
...
+        Ok(())
+    }
+
+    pub async fn reserve_nonce(&self) -> Result<u64> {
+        let current_nonce = self.get_current_nonce().await?;
+
+        let mut local_nonce = self
+            .nonce
+            .lock()
+            .map_err(|_| anyhow::anyhow!("Mutex lock error during nonce update"))?;
```
Comment (karim-en) [inline omni-relayer/src/utils/nonce.rs:63]: Why we need to update it here and also why not just to call `resync_nonce`?

Comment (frolvanya) [reply omni-relayer/src/utils/nonce.rs:63]: because resync nonce takes nonce from rpc and we will mess up pending (next) transactions. That's why we need it update by 1

File: omni-relayer/src/workers/near.rs [hunk 3]
```diff
@@ -257,9 +280,25 @@ pub async fn finalize_transfer(
                                 return;
                             }
                             ChainKind::Eth | ChainKind::Base | ChainKind::Arb => {
+                                let nonce = match evm_nonces
+                                    .reserve_nonce(message_payload.recipient.get_chain())
```
Comment (karim-en) [inline omni-relayer/src/workers/near.rs:284]: There is a chance that the nonce was reserved, but the transaction was rejected by the RPC.
Or what will happen if the transaction fails during the gas estimation, in this case, the transaction will not even submitted

Comment (frolvanya) [reply omni-relayer/src/workers/near.rs:288]: in this case failed tx will be deleted and nonce will be resynced before the next batch https://github.com/Near-One/omni-bridge/pull/243/commits/4de392dbe489d828ba8bd90d11d7d8d3939e1c34

**Comment by karim-en** [comment]
@race-of-sloths score 13

**Review by karim-en — APPROVED** [review]
