### PR TITLE
fix: Remove excess storage deposit in test

### LINKED ISSUE #94: [OmniBridge]: `required_balance_for_fin_transfer` returns the insufficient amount
The correct fix would allow the integration test (`near/omni_tests/src/lib.rs`) to run correctly without the lines 223-224.

### PR DESCRIPTION
**Pull request by r-near**
With https://github.com/Near-One/omni-bridge/pull/117, we no longer need this adjustment for extra NEAR.

Closes #94

### CODE REVIEW

**Comment by karim-en** [comment]
LGTM, but potentially this will be out of dated due to the changes in this [PR](https://github.com/Near-One/omni-bridge/pull/117)

**Comment by r-near** [comment]
> LGTM, but potentially this will be out of dated due to the changes in this [PR](https://github.com/Near-One/omni-bridge/pull/117)

Yep! Looks like that PR fixed the issue. Awesome to see, I just updated the PR to remove the extraneous storage deposit.

File: near/omni-tests/src/lib.rs [hunk 1]
```diff
@@ -219,9 +219,7 @@ mod tests {
         let required_deposit_for_fin_transfer = NEP141_DEPOSIT
             .saturating_mul(storage_deposit_accounts.len() as u128)
             .saturating_add(required_balance_for_fin_transfer)
-            .saturating_add(NearToken::from_yoctonear(2))
-            // This is a temporary value to cover the issue with incorrect storage deposit calculation
-            .saturating_add(NearToken::from_yoctonear(1250000000000000000000));
+            .saturating_add(NearToken::from_yoctonear(2));
```
Comment (karim-en) [inline near/omni-tests/src/lib.rs:222]: Let's improve the UX and add these two yocto to the `pub fn required_balance_for_fin_transfer(&self) -> NearToken`

**Review by karim-en — CHANGES_REQUESTED** [review]

File: near/omni-tests/src/lib.rs (hunk 1 above)
Comment (r-near) [reply near/omni-tests/src/lib.rs]: Thanks to @olga24912 this change was made in #138. I've updated the PR to remove the excess storage deposit.

File: near/omni-tests/src/fin_transfer.rs [hunk 2]
```diff
@@ -195,9 +195,7 @@ mod tests {
         let required_deposit_for_fin_transfer = NEP141_DEPOSIT
             .saturating_mul(storage_deposit_accounts.len() as u128)
             .saturating_add(required_balance_for_fin_transfer)
-            .saturating_add(NearToken::from_yoctonear(2))
-            // This is a temporary value to cover the issue with incorrect storage deposit calculation
-            .saturating_add(NearToken::from_yoctonear(1250000000000000000000));
+            .saturating_add(NearToken::from_yoctonear(2));
```
Comment (olga24912) [inline near/omni-tests/src/fin_transfer.rs:198]: This line we can remove as well. Now it is included in required_balance_for_fin_transfer. 
https://github.com/Near-One/omni-bridge/pull/138/files

**Review by olga24912 — CHANGES_REQUESTED** [review]

**Review by karim-en — APPROVED** [review]
