### PR TITLE
fix: restart ws connection to rpc when it was dropped

### LINKED ISSUE #220: [OmniRelayer]: restart web socket connection for indexers if it was dropped
Recently relayer died because Eth indexer's ws connection stopped working:

Image

### PR DESCRIPTION
**Pull request by frolvanya**
image

In the worst case scenario when there's no network connection relayer will try to reconnect to rpc providers every 5 seconds instead of dying silently

closes #220

### CODE REVIEW

File: omni-relayer/src/startup/evm.rs [hunk 1]
```diff
@@ -110,19 +119,50 @@ pub async fn start_indexer(
...
+            .on_ws(WsConnect::new(&rpc_ws_url))
+            .await
+        {
+            Ok(provider) => provider,
+            Err(err) => {
+                error!(
+                    "{chain_kind:?} WebSocket connection failed: {}, retrying...",
+                    err
+                );
+                tokio::time::sleep(tokio::time::Duration::from_secs(5)).await;
```
Comment (karim-en) [inline omni-relayer/src/startup/evm.rs:133]: This can be refactored using macros.
See this example 
https://github.com/Near-One/eth2-on-near-client-validator/blob/48fe316da190573f523e37700c35ad557b38db67/src/eth2_validator.rs#L15

**Review by karim-en — CHANGES_REQUESTED** [review]

**Review by karim-en — APPROVED** [review]
